esphome:
  name: reterminal
  friendly_name: Reterminal

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sWssxLQDZS++nDnjp3KB7fRLLXncQX16VyXlgXyEYfo="

ota:
  - platform: esphome
    password: "72535808d696d564e7a72b119a305521"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Reterminal Fallback Hotspot"
    password: "GFLsOwWWKTYA"

captive_portal:
    