esphome:
  name: reterminale1002
  friendly_name: reterminalE1002

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Gw7IxjP9ga1b32aeP/RYCcme0GEd1h/w+UqitfzvGrc="

ota:
  - platform: esphome
    password: "1426f10a47b429f4f6d64dc7e16f1092"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Reterminale1002 Fallback Hotspot"
    password: "FedcW2U0Xgy0"

captive_portal:
    