substitutions:
  name: apollo-msr-2-f8ba08
  friendly_name: Apollo MSR-2 f8ba08
packages:
  ApolloAutomation.MSR-2_Factory: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2_Factory.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: qPnnTB3z/P7loC+Y0IzZExKismG1xCZWs2R+P+v/RjQ=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
