blueprint:
  name: Aqara H2 EU Single rocker (WS-K07E)
  description: " Only top buttons can toggle the relays, and double/hold/release actions
    can only be enabled for the bottom buttons.\n \n In `control_relay` mode, `single_*`
    events are always sent, alongside with actual relay toggle. In `decoupled` mode,
    the same events are sent, but the relay toggle is disabled.\n \n When `Multi click`
    is disabled, only `single_*` events are sent. To have access to `double_*`, `hold_*`
    and `release_*` events, `Multi click` must be enabled, for the respective button.\n
    Also, `release_*` only and always follows `hold_*` events. If button is not held
    enough to trigger `hold_*`, there will also not be a `release_*` event.\n \n Enabling
    `Multi click` will add ~1s of additional delay to event triggering, as the switch
    waits for further button presses.\n Switches connected without neutral wire also
    have slower event triggering, compared to switches with neutral wire connected.\n "
  domain: automation
  input:
    event:
      name: Event
      description: Zigbee2MQTT controller event
      selector:
        entity:
          integration: mqtt
          domain:
          - event
          multiple: false
          reorder: false
    helper_last_controller_event:
      name: Helper - Last Controller Event
      description: Input Text Helper to store the last event
      selector:
        entity:
          domain:
          - input_text
          multiple: false
          reorder: false
    helper_last_event_time:
      name: Helper - Last Event Timestamp
      description: Input Text Helper to store the last timestamp
      selector:
        entity:
          domain:
          - input_text
          multiple: false
          reorder: false
    cooldown_seconds:
      name: Cooldown (seconds)
      description: Minimum time before accepting duplicate events
      default: 1
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.1
          unit_of_measurement: seconds
          mode: slider
    single_up:
      name: Single Up
      default: []
      selector:
        action: {}
    single_down:
      name: Single Down
      default: []
      selector:
        action: {}
    double_down:
      name: Double Down
      default: []
      selector:
        action: {}
    hold_down:
      name: Hold Down
      default: []
      selector:
        action: {}
    release_down:
      name: Release Down
      default: []
      selector:
        action: {}
  source_url: https://gist.github.com/Jonybat/f93cbff0be1733f37e5ac5b95f8c10c7
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input event
  not_from:
  - unknown
  - unavailable
  not_to:
  - unknown
  - unavailable
action:
- variables:
    helper_last_controller_event: !input helper_last_controller_event
    helper_last_event_time: !input helper_last_event_time
    cooldown: !input cooldown_seconds
    command: '{{ trigger.to_state.attributes.event_type }}'
    prev_command: '{{ states(helper_last_controller_event) }}'
    prev_time: '{{ states(helper_last_event_time) | float(0) }}'
    now_time: '{{ now().timestamp() }}'
    elapsed: '{{ now_time - prev_time }}'
- condition: or
  conditions:
  - condition: template
    value_template: '{{ command != prev_command }}'
  - condition: template
    value_template: '{{ elapsed > cooldown }}'
- service: input_text.set_value
  data:
    entity_id: !input helper_last_controller_event
    value: '{{ command }}'
- service: input_text.set_value
  data:
    entity_id: !input helper_last_event_time
    value: '{{ ''%.6f'' | format(now_time) }}'
- choose:
  - conditions:
    - condition: template
      value_template: '{{ command == ''single_up'' }}'
    sequence: !input single_up
  - conditions:
    - condition: template
      value_template: '{{ command == ''single_down'' }}'
    sequence: !input single_down
  - conditions:
    - condition: template
      value_template: '{{ command == ''double_down'' }}'
    sequence: !input double_down
  - conditions:
    - condition: template
      value_template: '{{ command == ''hold_down'' }}'
    sequence: !input hold_down
  - conditions:
    - condition: template
      value_template: '{{ command == ''release_down'' }}'
    sequence: !input release_down
